<center>
    <a href="https://www.aims-senegal.org/" ><img src="aimssn_logo.png" style="float:center; max-width: 600px; display: inline" alt="IMSP"/> </a>
    </center>
    
#    <center> <b> <span style="color:orange;" >  `Python for Scientific Computing and Software Engineering ` </span> </b></center>


## <center> <b> <span style="color:orange;"> An Initiation to Programming using Python (Init2Py) </span> </b></center>

### <center> <b> <span style="color:blue;"> Practicals: Variables, Types & Operations </span> </b></center>

**Exercise 00:**  

> 1. Declare a variable `firstname` and assign it a value.
> 2. Declare a `lastname` variable and assign a value to it.
> 3. Declare a `full_name` variable and assign it a value.
> 4. Declare a `country` variable and assign it a value.
> 5. Declare a variable `city` and assign it a value.
> 6. Declare a `age` variable and assign it a value.
> 7. Declare a variable `year` and assign it a value.
> 8. Declare a variable `is_marrie` and assign it a value.
> 9. Declare a variable `is_true` and assign it a value.

> For each of the above variable, display the value it contains using the `print()` function.




In [6]:
firstname="Haby"
lastname="SOW"
full_name="Haby SOW"
country="senegal"
city="Dakar"
age="27"
year="1994"
is_marrie="No"
is_true="True"
print(firstname,lastname,full_name,country,city,age,year,is_marrie,is_true)



Haby SOW Haby SOW senegal Dakar 27 1994 No True


**Exercise 01:** 
> Check the data type of all your variables using the built-in function `type()`.**


In [21]:
firstname="Haby"
type(firstname)
lastname="SOW"
type(lastname)
full_name="Haby SOW"
type(full_name)
country="senegal"
type(country)
city="Dakar"
type(city)
age="27"
type(age)
year="1994"
type(year)
is_marrie="No"
type(is_marrie)
is_true="True"
type(is_true)



str

**Exercise 02:** 
> Calculate the value of $y$ ($y = x^2 + 6x + 9$). Try using different values of $x$ and determine at what value of $x$ will $y$ be equal to 0.**

In [3]:
for x in range(-3,3):
    
    y=x**2+6*x+9
    print(y)




0
1
4
9
16
25


**Exercise 03:** 
>    
     1. Declare your age as an integer variable
     2. Declare your height as a float variable
     3. Declare a variable that stores the base and height of a triangle. Calculate the area of this triangle (area = 0.5 x b x h).

In [3]:
age=18
age=int(age)
taille=1.78
taille=float(taille)
base=2
store=(base,taille)
area=0.5*store[0]*store[1]
print(area)

1.78


**Exercise 04:** 
> **Write a small code that asks the user to enter the side $a$, the side $b$ and the side $c$ of a triangle. Calculate the perimeter of the triangle (perimeter = a + b + c).**

In [9]:
a=int(input("donner le coter a"))
b=int(input("donner le coter b"))
c=int(input("donner le coter c"))

perimetre=a++b++c

print(perimetre)

donner le coter a2
donner le coter b5
donner le coter c4
11


**Exercise 05:** 
> **Obtain the length and width of a rectangle using the prompt. Calculate its `area`and its `perimeter`.**

In [5]:
L=int(input("entrer la longueur du rectangle"))
l=int(input("entrer la largeur du rectangle"))
surface=L*l
print(surface)

entrer la longueur du rectangle2
entrer la largeur du rectangle4
8


**Exercice 06:** 
> **Obtenez le rayon d'un cercle en utilisant l'invite. Calculez l'aire (aire = pi x r x r) et la circonférence (c = 2 x pi x r) où pi = 3,14.**

In [12]:
r=float(input("donner le rayon r "))
pi=3.14
aire=pi*r*r
c=2*pi*r
print(aire,r)

donner le rayon r 2
12.56 2.0


**Exercice 07:**
> **Calculez la pente, l'ordonnée à l'origine en x et l'ordonnée à l'origine en $y$ de $y = 2x -2$.**

In [18]:
x1=int(input("x1 "))
x2=int(input("x2 "))
y1=int(input("y1 "))
y2=int(input("y2 "))
a=(y2-y1)/(x2-x1)
b=y1-a*x1
print(x1,y1)


x1 1
x2 2
y1 3
y2 4
1 3


In [19]:
x=int(input("x"))
a=2
b=-2
y=a*x+b
print(y)

x5
8


**Exercice 08:** 
> **Rédigez un script qui demande à l'utilisateur d'entrer les heures et le taux horaire. Calculez la rémunération de la personne ?**

In [7]:
h=int(input("entrer vos heures de travail dans le mois"))
s=float(input("entrer votre salaire"))
renumeration=s/h
print(renumeration)

entrer vos heures de travail dans la semaine25
entrer votre salaire200000
8000.0


**Exercice 09:** 
> **Écrivez un script qui demande à l'utilisateur d'entrer le nombre d'années. Calculez le nombre de secondes qu'une personne peut vivre. Supposons qu'une personne puisse vivre cent ans.**

In [5]:
a=int(input("donner votre age"))
s=1
minu=60*s
H=60*minu
jr=24*H
ans=365*jr
nbr_s=a*ans
print(nbr_s)

donner votre age100
3153600000


**Exercice 10:** 
> **Écrivez un script Python qui affiche le tableau suivant**

    1 1 1 1 1
    
    2 1 2 4 8
    
    3 1 3 9 27
    
    4 1 4 16 64
    
    5 1 5 25 125

In [7]:
import numpy as np

Tab=np.array([
    [1, 1, 1, 1, 1],
    [2, 1, 2, 4, 8],
    [3, 1, 3, 9, 27],
    [4, 1, 4, 16, 64],
    [5, 1, 5, 25, 125]
])
print(Tab)

[[  1   1   1   1   1]
 [  2   1   2   4   8]
 [  3   1   3   9  27]
 [  4   1   4  16  64]
 [  5   1   5  25 125]]


**Exercise 11:** 
>**Assign the variables `time` and `distance` with the values $6.892$ and $19.7$. Calculate and display the value of the speed. Improve the display by imposing a digit after the decimal point.**

In [9]:
t=6.892
D=19.7
V=D/t
print(V)
Varrondi= round(V, 2)
print(Varrondi)

2.8583865351131745
2.86


**Exercice 12:** 
> **Écrire un programme qui, à partir de la saisie d’un rayon et d’une hauteur, calcule levolume d’un cône droit.**

In [11]:
r=float(input("donner la valeur de rayon"))
h=float(input("donner la valeur de la hauteur"))
pi=3.14
B=pi*r*r
VCONE=1/3*B*h
print(VCONE)

donner la valeur de rayon2
donner la valeur de la hauteur12
50.239999999999995


**Exercise 13:** 
> **The user gives a positive integer and the program announces how many times in a row this integer is divisible by 2.**

In [ ]:
x=int(input("donner la valeur de x"))
i=2
while  (x % i ==0):
  print(i)
  x = x //2


**Exercise 14:** 
>**The user gives an integer between 2 and 12, the program gives the number of ways to do this by rolling two dice.

**Exercice 15:** 
> **Utilisez la fonction d'entrée intégrée `input()` pour obtenir le `_prénom_`, le `_nom_`, le `_pays_d_origine` et l'`_age_` d'un utilisateur et stockez la valeur dans les noms des variables correspondantes.**

In [14]:
prenom=str(input("donner votre prenom"))
nom=str(input("donner votre nom"))
PO=str(input("donner votre pays d'origine"))
age=int(input("donner votre age"))
val_prenom=prenom
val_nom=nom
val_PO=PO
val_age=age
print(val_prenom,val_nom,val_PO,val_age)


donner votre prenomhaby
donner votre nomsow
donner votre pays d'originesen
donner votre age45
haby sow sen 45


**Exercice 16:** 

**Déclarer $5$ comme `num_one` et $4$ comme `num_two`**

   1. Additionner `num_one` et `num_two` et affecter la valeur à une variable `totale`.
   2. Soustraire `num_two` de `num_one` et affecter la valeur à une variable `diff`.
   3. Multipliez le `num_one` et le `num_two` et attribuez la valeur à une variable `produit`.
   4. Divisez le `num_one` par le `num_two` et attribuez la valeur à une variable `division`.
   5. Calculez `num_one` à la puissance de `num_two` et attribuez la valeur à une variable `exp`.

In [17]:
num_one=5
num_two=4
total=num_one+num_two
diff=num_two-num_one
produit=num_one*num_two
division=num_one/num_two
exp=num_one**num_two
print(total,diff,produit,division,exp)

9 -1 20 1.25 625


<center> <b> <span style="color:orange;"> 🎉 FÉLICITATIONS! / CONGRATULATIONS! 🎉 </span> </b></center>